name: Biome

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  biome:
    name: Run biome checking
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Biome
        run: npm install -g @biomejs/biome

      - name: Run Biome Check
        run: biome check --write
