name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install npm-check-updates
      run: npm install -g npm-check-updates

    - name: Run update dependencies
      run: ncu -u

    - name: Commit and push changes
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add package.json
        git commit -m "Update dependencies"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
